language: ruby
script: bundle exec rake
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- 2.1.5
- ruby-head
- rbx-2
- jruby-19mode
- jruby-head
matrix:
  allow_failures:
  - rvm: 1.9.3
  - rvm: jruby-head
  - rvm: jruby-19mode
  - rvm: ruby-head
  - rvm: rbx-2
before_script:
- cp spec/functional/initializer.rb.ci spec/functional/initializer.rb
